services:
  postgres:
    image: postgres:15
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=next-full-stack
      - POSTGRES_HOST_AUTH_METHOD=trust
